/**
 * Project configuration
 * This file is auto-generated by pipecat-cli
 */

import type { DailyConnectionEndpoint } from '@pipecat-ai/daily-transport';
import type { APIRequest } from '@pipecat-ai/client-js';

export type TransportType = 'daily' | 'smallwebrtc';

export const AVAILABLE_TRANSPORTS: TransportType[] = [
  'smallwebrtc',
];

export const TRANSPORT_LABELS: Record<TransportType, string> = {
  daily: 'Daily',
  smallwebrtc: 'SmallWebRTC',
};

export const DEFAULT_TRANSPORT: TransportType = 'smallwebrtc';

// Default to same-origin (unified server serves frontend + proxies WebRTC).
// In dev mode with Vite on :5173, set VITE_BOT_START_URL to point at the MCP server.
const botStartUrl =
  import.meta.env.VITE_BOT_START_URL || `${window.location.origin}/start`;
const botStartPublicApiKey = import.meta.env.VITE_BOT_START_PUBLIC_API_KEY;

const dailyConfig: DailyConnectionEndpoint = {
  endpoint: botStartUrl,
  requestData: {
    createDailyRoom: true,
    dailyRoomProperties: { start_video_off: true },
    transport: "daily",
  },
};

if (botStartPublicApiKey) {
  dailyConfig.headers = new Headers({
    Authorization: `Bearer ${botStartPublicApiKey}`,
  });
}

const smallWebRTCConfig: APIRequest = {
  endpoint: botStartUrl,
  requestData: {
    createDailyRoom: false,
    enableDefaultIceServers: true,
    transport: "webrtc",
  },
};

if (botStartPublicApiKey) {
  smallWebRTCConfig.headers = new Headers({
    Authorization: `Bearer ${botStartPublicApiKey}`,
  });
}

export const TRANSPORT_CONFIG: Record<
  TransportType,
  DailyConnectionEndpoint | APIRequest
> = {
  daily: dailyConfig,
  smallwebrtc: smallWebRTCConfig,
};